# meta-batana — batana 设备自定义 Yocto layer

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "batana"
BBFILE_PATTERN_batana = "^${LAYERDIR}/"
BBFILE_PRIORITY_batana = "10"

# 与 scarthgap 对齐（meta-rockchip / meta-qt6 同分支）
LAYERSERIES_COMPAT_batana = "scarthgap"
